# -*- ispell-dictionary: "castellano" -*-

#+SETUPFILE: ./probl-es.org

#+TITLE: {{{unit01}}}: ejercicios


* Q.1

*(Wooldridge: Ejemplo 2.5, pág. 35).* La base de datos \data{vote1}
contiene información sobre las elecciones de Estados Unidos de 1988
con las que se renovó la Cámara de Representantes. En concreto, se
dispone de información sobre los resultados electorales en 173
distritos electorales en los que sólo se presentaban un candidato del
Partido Demócrata y otro del Partido Republicano:

- \voteA: es el porcentaje de votos recibidos por uno de los
  candidatos, el candidato A.

- \expendA, \expendB: gastos de campaña, en miles de dólares, del
  candidato A y del candidato B, respectivamente.

- \democA: variable ficticia que toma el valor 1 si A es el candidato del
  Partido Demócrata.

- \prtystrA: el porcentaje de votos que obtuvo el partido de A en las
  elecciones presidenciales más recientes. Con esta variable se trata
  de medir la fuerza del partido del candidato A en el distrito
  electoral.

Con estas variables se han estimado por mínimos cuadrados ordinarios
los modelos de regresión:
#+begin_export latex
\begin{gather*}
  \begin{regeq}
    \begin{aligned}
      \voteAhat =
      \MoveEqLeft
      \coef       {49.6}(1.43)
      \coef[\expendA]{ 0.0383}(0.00339)
      \coef[\expendB]{-0.0361}(0.00311)
    \end{aligned}
  \end{regeq} \tag{Modelo 1} \\
  n = 173 \qquad \SER = 11.575 \qquad \Rsq = 0.530
\end{gather*}
#+end_export

#+begin_export latex
\begin{gather*}
  \begin{regeq}
    \begin{aligned}
      \voteAhat =
      \MoveEqLeft
      \coef         {17.0}(5.22)
      \coef[\expendA]  { 0.0318}(0.00320)
      \coef[\expendB]  {-0.0301}(0.00296) \\
      & \coef[\democA]{ 9.38}(1.84)
      \coef[\prtystrA]  { 0.555}(0.0921)
    \end{aligned}
  \end{regeq} \tag{Modelo 2} \\
  n = 173 \qquad \SER = 10.380 \qquad \Rsq = 0.626
\end{gather*}
#+end_export
#+latex: \clearpage{}
Utilizando un nivel de significación $\alpha = 5\%$ cuando sea
necesario, responda a las siguientes cuestiones:

a) Interprete las estimaciones de los parámetros del Modelo 2.

b) Contraste la significación individual de las variables explicativas
   del Modelo 2.

c) Obtenga intervalos de confianza para cada una de las pendientes del
   Modelo 2.

d) Contraste la significación de la regresión correspondiente al
   Modelo 2.

e) Contraste la significación conjunta de las variables $\democA$ y
   $\prtystrA$.

f) Si quisiera contrastar la hipótesis de los gastos de campaña de
   cada uno de los candidatos tienen efectos de signo opuesto pero de
   igual magnitud, ¿cuál sería el modelo restringido que tendría que
   estimar?

g) ¿Cómo podría contrastar la hipótesis del apartado anterior usando
   un contraste de significación conjunta?

** Answer

Por hacer

* Q.2

Considere el modelo de regresión:
#+begin_export latex
\[
  y =
  \beta_{0} + \beta_{1} x_{1} + \beta_{2} x_{2} +
  \beta_{3} x_{3} + u.
\]
#+end_export
Describa el modelo restringido que debería de estimar y el contraste que usaría para contrastar las siguientes hipótesis:

a) $H_0\!: \beta_1 = 2 \beta_2$.
b) $H_0\!: \beta_2 + \beta_3 = 1$.
c) $H_0\!: \beta_1 = 1, \beta_2 + \beta_3= 1$.

¿Cómo podría contrastar cada una de esas hipótesis usando contrastes
de significación conjunta?

** Answer

Por hacer
